hamiltonian: custom
compute_maximum_time: false
compute_reference: true
n_sites: 6
terms:
  - [0, 1, 'X', 'X', 0.5]
  - [1, 2, 'Y', 'Y', 0.3]
  - [2, 3, 'Z', 'Z', 0.8]

disordered: false
degree: 2
n_repetitions: 10
t: 2.
max_bond_dim: 128
compress: true
degree_thres: 2
n_rep_thres: 8
fac_thres: 10
reference_number_start: 10
reference_seed: 
- 0